# .github/workflows/netlify.yml
name: Build and Deploy to Netlify
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v2

      - name: Install dependencies
        run: npm install

      - name: Test Applicant (Will test more later)
        run: npm test

      - name: Build
        run: npm run build

      # ( Build to ./dist or other directory... )

      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v3.0
        with:
          publish-dir: "./dist"
          production-branch: master
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: "Deploy from GitHub Actions"
          enable-pull-request-comment: false
          enable-commit-comment: true
          overwrites-pull-request-comment: true
        env:
          NETLIFY_AUTH_TOKEN: "nfp_sUK5tU5ducB7BB9BswAMCRDMb1YbXd8t5454"
          NETLIFY_SITE_ID: "38d129a2-4db9-4683-bf17-76e85b53cdaa"
        timeout-minutes: 1
